FROM ubuntu/apache2:2.4-22.04_beta

RUN apt-get update -y && apt-get install php php-mysql php-zip php-curl php-xml php-json php-mbstring libapache2-mod-php -y

RUN rm /var/www/html/index.html

COPY apache/vhost-autoshop.conf /etc/apache2/sites-avaliable/

COPY app /var/www/html/



#COPY apache/.htpasswd /var/www/html/

EXPOSE 80
