version: '3.1'
services:
  web-001:
    container_name: web-001
    hostname: web-001
    build:
      dockerfile: ./Dockerfile_apache
      tags:
        - web-img
    ports:
      - "8080:80/tcp"
    restart: always
    networks:
      autoshop-net:
        ipv4_address: 172.16.40.10
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
  
  mysql-001:
    container_name: mysql-001
    hostname: mysql-001
    build:
      dockerfile: ./Dockerfile_mysql
      tags:
        - mysql-img
    ports:
      - "3306:3306/tcp"
    restart: always
    networks:
      autoshop-net:
        ipv4_address: 172.16.40.20
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    networks:
      autoshop-net:
        ipv4_address: 172.16.40.30

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    container_name: kibana
    hostname: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      autoshop-net:
        ipv4_address: 172.16.40.40

  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.1
    container_name: logstash
    hostname: logstash
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/driver:/usr/share/logstash/driver
    ports:
      - "5044:5044"
    depends_on:
      - elasticsearch
    networks:
      autoshop-net:
        ipv4_address: 172.16.40.50

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.10.1
    container_name: filebeat
    hostname: filebeat
    user: root
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - logstash
    networks:
      autoshop-net:
        ipv4_address: 172.16.40.60
  
  metricbeat:
    image: docker.elastic.co/beats/metricbeat:7.10.1
    container_name: metricbeat
    hostname: metricbeat
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
      - ./metricbeat/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
    depends_on:
      - elasticsearch
    networks:
      autoshop-net:
        ipv4_address: 172.16.40.70

networks:
  autoshop-net:
    name: autoshop-net
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.40.0/24
