#############################################
# ** Fichero configuración del sitio web ** #
#############################################

<VirtualHost *:80>
    # ServerName configurado para evitar la advertencia sobre el nombre de dominio completo.
    ServerName 172.16.40.10
    
    # Correo electrónico del administrador.
    ServerAdmin webmaster@localhost

    # Ruta del documento.
    DocumentRoot /var/www/html/app

    # Especificación del fichero índice.
    DirectoryIndex index.php

    # Configuración de seguridad para el archivo config.json
    <Files "config.json">
        # Para restringir el acceso solo al administrador, descomenta las siguientes líneas.
        # AuthName "Acesso Restringido a esta información"
        # AuthType Basic
        # AuthUserFile "/var/www/html/app/.htpasswd"
        # Require user admin

        # Prohibir completamente el acceso al archivo config.json (opción predeterminada).
        Require all denied
        
        # Si deseas que sea visible (no recomendado), descomenta la siguiente línea.
        # Require all granted
    </Files>

    # Configuración para la página de estado del servidor.
    <Location /server-status>
        SetHandler server-status
        # Permitir acceso solo desde ciertas IPs
        Require ip 172.16.40.70 172.16.40.1
        
        # Si deseas permitir acceso desde cualquier IP (menos seguro), usa:
        # Require all granted
    </Location>

    # Nivel de registro de Apache.
    LogLevel info

    # Página de error personalizada para errores 403.
    ErrorDocument 403 /access-denied.html

    # Configuración de los registros de errores y de acceso.
    ErrorLog /dev/stderr
    CustomLog /dev/stdout combined

</VirtualHost>